// 显式 schema 迁移语句。
// 新版本从 v1 开始；所有语句幂等，支持空库直接创建。

export interface Migration {
  version: number;
  statements: readonly string[];
}

export const MIGRATIONS: readonly Migration[] = [
  {
    version: 1,
    statements: [
      // 迁移记录表自身
      `CREATE TABLE IF NOT EXISTS schema_migrations (
         version INTEGER PRIMARY KEY,
         applied_at INTEGER NOT NULL
       )`,

      // 管理员
      `CREATE TABLE IF NOT EXISTS admin_users (
         id TEXT PRIMARY KEY,
         username TEXT NOT NULL UNIQUE,
         password_hash TEXT NOT NULL,
         display_name TEXT,
         enabled INTEGER NOT NULL DEFAULT 1,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         last_login_at INTEGER
       )`,
      `CREATE TABLE IF NOT EXISTS admin_sessions (
         id TEXT PRIMARY KEY,
         admin_user_id TEXT NOT NULL,
         session_hash TEXT NOT NULL UNIQUE,
         expires_at INTEGER NOT NULL,
         created_at INTEGER NOT NULL,
         last_seen_at INTEGER NOT NULL,
         FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE CASCADE
       )`,
      `CREATE INDEX IF NOT EXISTS admin_sessions_admin_idx ON admin_sessions(admin_user_id)`,
      `CREATE INDEX IF NOT EXISTS admin_sessions_expires_idx ON admin_sessions(expires_at)`,
      `CREATE TABLE IF NOT EXISTS login_attempts (
         id TEXT PRIMARY KEY,
         username TEXT NOT NULL,
         ip TEXT NOT NULL,
         success INTEGER NOT NULL DEFAULT 0,
         created_at INTEGER NOT NULL
       )`,
      `CREATE INDEX IF NOT EXISTS login_attempts_created_at_idx ON login_attempts(created_at)`,
      `CREATE INDEX IF NOT EXISTS login_attempts_username_idx ON login_attempts(username, created_at)`,
      `CREATE INDEX IF NOT EXISTS login_attempts_ip_idx ON login_attempts(ip, created_at)`,

      // 系统设置
      `CREATE TABLE IF NOT EXISTS admin_settings (
         id TEXT PRIMARY KEY,
         circuit_breaker_enabled INTEGER NOT NULL DEFAULT 1,
         circuit_breaker_failure_threshold INTEGER NOT NULL DEFAULT 5,
         circuit_breaker_base_cooldown_ms INTEGER NOT NULL DEFAULT 60000,
         circuit_breaker_max_cooldown_ms INTEGER NOT NULL DEFAULT 600000,
         circuit_breaker_half_open_success_count INTEGER NOT NULL DEFAULT 2,
         endpoint_health_probe_enabled INTEGER NOT NULL DEFAULT 1,
         endpoint_health_probe_interval_ms INTEGER NOT NULL DEFAULT 3600000,
         endpoint_health_probe_timeout_ms INTEGER NOT NULL DEFAULT 10000,
         endpoint_health_probe_degraded_latency_ms INTEGER NOT NULL DEFAULT 5000,
         first_token_timeout_ms INTEGER NOT NULL DEFAULT 15000,
         content_log_enabled INTEGER NOT NULL DEFAULT 0,
         content_log_retention_days INTEGER NOT NULL DEFAULT 7,
         content_log_max_payload_bytes INTEGER NOT NULL DEFAULT 100000,
         public_endpoints_base_path TEXT NOT NULL DEFAULT '/v1',
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,

      // 应用与 Consumer Key
      `CREATE TABLE IF NOT EXISTS apps (
         id TEXT PRIMARY KEY,
         name TEXT NOT NULL UNIQUE,
         description TEXT,
         enabled INTEGER NOT NULL DEFAULT 1,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,
      `CREATE TABLE IF NOT EXISTS consumer_keys (
         id TEXT PRIMARY KEY,
         app_id TEXT NOT NULL,
         name TEXT NOT NULL,
         key_hash TEXT NOT NULL UNIQUE,
         key_prefix TEXT NOT NULL,
         key_suffix TEXT NOT NULL DEFAULT '',
         access_mode TEXT NOT NULL DEFAULT 'all',
         enabled INTEGER NOT NULL DEFAULT 1,
         revoked_at INTEGER,
         last_used_at INTEGER,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
       )`,
      `CREATE INDEX IF NOT EXISTS consumer_keys_app_idx ON consumer_keys(app_id)`,
      `CREATE TABLE IF NOT EXISTS consumer_key_access (
         id TEXT PRIMARY KEY,
         consumer_key_id TEXT NOT NULL,
         target_type TEXT NOT NULL,
         target_id TEXT NOT NULL,
         created_at INTEGER NOT NULL,
         FOREIGN KEY (consumer_key_id) REFERENCES consumer_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS consumer_key_access_unique ON consumer_key_access(consumer_key_id, target_type, target_id)`,
      `CREATE INDEX IF NOT EXISTS consumer_key_access_target_idx ON consumer_key_access(target_type, target_id)`,

      // Provider Preset（本地自定义）
      `CREATE TABLE IF NOT EXISTS provider_presets (
         id TEXT PRIMARY KEY,
         source TEXT NOT NULL DEFAULT 'local',
         name TEXT NOT NULL,
         provider_type TEXT NOT NULL,
         descriptor_json TEXT NOT NULL,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,

      // 上游 Key
      `CREATE TABLE IF NOT EXISTS upstream_keys (
         id TEXT PRIMARY KEY,
         name TEXT NOT NULL UNIQUE,
         provider_preset_id TEXT,
         provider_type TEXT NOT NULL,
         base_url TEXT NOT NULL,
         auth_type TEXT NOT NULL DEFAULT 'pat',
         api_key_ciphertext TEXT NOT NULL,
         api_key_prefix TEXT NOT NULL,
         auth_config_ciphertext TEXT,
         default_headers_json TEXT,
         extra_headers_json TEXT,
         extra_params_json TEXT,
         supported_models_json TEXT NOT NULL DEFAULT '[]',
         endpoints_json TEXT,
         display_order INTEGER NOT NULL DEFAULT 1000,
         enabled INTEGER NOT NULL DEFAULT 1,
         frozen INTEGER NOT NULL DEFAULT 0,
         frozen_reason TEXT,
         cooldown_until INTEGER,
         last_health_status TEXT,
         last_error_code TEXT,
         last_error_message TEXT,
         last_used_at INTEGER,
         sticky_session_ttl_ms INTEGER NOT NULL DEFAULT 300000,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,
      `CREATE TABLE IF NOT EXISTS upstream_key_quotas (
         id TEXT PRIMARY KEY,
         upstream_key_id TEXT NOT NULL UNIQUE,
         period TEXT NOT NULL,
         request_limit INTEGER,
         input_token_limit INTEGER,
         output_token_limit INTEGER,
         total_token_limit INTEGER,
         enabled INTEGER NOT NULL DEFAULT 1,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE INDEX IF NOT EXISTS upstream_key_quotas_key_idx ON upstream_key_quotas(upstream_key_id)`,
      `CREATE TABLE IF NOT EXISTS upstream_key_counters (
         id TEXT PRIMARY KEY,
         upstream_key_id TEXT NOT NULL,
         period TEXT NOT NULL,
         period_started_at INTEGER NOT NULL,
         period_ends_at INTEGER NOT NULL,
         request_count INTEGER NOT NULL DEFAULT 0,
         input_tokens INTEGER NOT NULL DEFAULT 0,
         output_tokens INTEGER NOT NULL DEFAULT 0,
         total_tokens INTEGER NOT NULL DEFAULT 0,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS upstream_key_counter_window ON upstream_key_counters(upstream_key_id, period, period_started_at)`,
      `CREATE INDEX IF NOT EXISTS upstream_key_counter_upstream_idx ON upstream_key_counters(upstream_key_id)`,
      `CREATE TABLE IF NOT EXISTS upstream_endpoint_health (
         id TEXT PRIMARY KEY,
         upstream_key_id TEXT NOT NULL,
         endpoint_base_url TEXT NOT NULL,
         delay_ms INTEGER,
         last_checked_at INTEGER,
         degraded INTEGER NOT NULL DEFAULT 0,
         error_code TEXT,
         error_message TEXT,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS upstream_endpoint_health_unique ON upstream_endpoint_health(upstream_key_id, endpoint_base_url)`,
      `CREATE INDEX IF NOT EXISTS upstream_endpoint_health_key_idx ON upstream_endpoint_health(upstream_key_id)`,
      `CREATE INDEX IF NOT EXISTS upstream_endpoint_health_degraded_idx ON upstream_endpoint_health(degraded, delay_ms)`,
      `CREATE INDEX IF NOT EXISTS upstream_endpoint_health_checked_idx ON upstream_endpoint_health(last_checked_at)`,

      // 目标命名空间与模型暴露
      `CREATE TABLE IF NOT EXISTS target_names (
         name TEXT PRIMARY KEY,
         target_type TEXT NOT NULL,
         target_id TEXT NOT NULL,
         created_at INTEGER NOT NULL
       )`,
      `CREATE INDEX IF NOT EXISTS target_names_target_idx ON target_names(target_type, target_id)`,
      `CREATE TABLE IF NOT EXISTS public_models (
         id TEXT PRIMARY KEY,
         name TEXT NOT NULL UNIQUE,
         display_name TEXT,
         description TEXT,
         enabled INTEGER NOT NULL DEFAULT 1,
         candidate_order_customized INTEGER NOT NULL DEFAULT 0,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,
      `CREATE TABLE IF NOT EXISTS public_model_candidates (
         id TEXT PRIMARY KEY,
         public_model_id TEXT NOT NULL,
         upstream_key_id TEXT NOT NULL,
         real_model_name TEXT NOT NULL,
         enabled INTEGER NOT NULL DEFAULT 1,
         priority INTEGER NOT NULL DEFAULT 100,
         weight INTEGER NOT NULL DEFAULT 1,
         ping_latency_ms INTEGER,
         ping_status TEXT,
         endpoint_url TEXT,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (public_model_id) REFERENCES public_models(id) ON DELETE CASCADE,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS public_model_candidate_unique ON public_model_candidates(public_model_id, upstream_key_id, real_model_name)`,
      `CREATE INDEX IF NOT EXISTS public_model_candidate_upstream_idx ON public_model_candidates(upstream_key_id)`,
      `CREATE TABLE IF NOT EXISTS model_groups (
         id TEXT PRIMARY KEY,
         name TEXT NOT NULL UNIQUE,
         display_name TEXT,
         description TEXT,
         enabled INTEGER NOT NULL DEFAULT 1,
         routing_policy TEXT NOT NULL DEFAULT 'priority',
         round_robin_counter INTEGER NOT NULL DEFAULT 0,
         mode TEXT NOT NULL DEFAULT 'manual',
         auto_preset TEXT,
         auto_region TEXT,
         auto_top_n INTEGER,
         auto_last_refreshed_at INTEGER,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,
      `CREATE TABLE IF NOT EXISTS model_group_members (
         id TEXT PRIMARY KEY,
         model_group_id TEXT NOT NULL,
         public_model_id TEXT NOT NULL,
         enabled INTEGER NOT NULL DEFAULT 1,
         priority INTEGER NOT NULL DEFAULT 100,
         weight INTEGER NOT NULL DEFAULT 1,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (model_group_id) REFERENCES model_groups(id) ON DELETE CASCADE,
         FOREIGN KEY (public_model_id) REFERENCES public_models(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS model_group_member_unique ON model_group_members(model_group_id, public_model_id)`,

      // 路由状态
      `CREATE TABLE IF NOT EXISTS sticky_bindings (
         id TEXT PRIMARY KEY,
         app_id TEXT NOT NULL,
         consumer_key_id TEXT NOT NULL,
         requested_target_name TEXT NOT NULL,
         conversation_fingerprint TEXT NOT NULL,
         upstream_key_id TEXT NOT NULL,
         real_model_name TEXT NOT NULL,
         hit_count INTEGER NOT NULL DEFAULT 0,
         last_used_at INTEGER NOT NULL,
         expires_at INTEGER NOT NULL,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE,
         FOREIGN KEY (consumer_key_id) REFERENCES consumer_keys(id) ON DELETE CASCADE,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS sticky_binding_unique ON sticky_bindings(app_id, consumer_key_id, requested_target_name, conversation_fingerprint)`,
      `CREATE INDEX IF NOT EXISTS sticky_binding_consumer_idx ON sticky_bindings(consumer_key_id, requested_target_name)`,
      `CREATE INDEX IF NOT EXISTS sticky_binding_expires_idx ON sticky_bindings(expires_at)`,
      `CREATE TABLE IF NOT EXISTS sticky_sessions (
         id TEXT PRIMARY KEY,
         consumer_key_id TEXT NOT NULL,
         requested_target_name TEXT NOT NULL,
         upstream_key_id TEXT NOT NULL,
         real_model_name TEXT NOT NULL,
         ttl_ms INTEGER NOT NULL,
         hit_count INTEGER NOT NULL DEFAULT 0,
         last_used_at INTEGER NOT NULL,
         expires_at INTEGER NOT NULL,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (consumer_key_id) REFERENCES consumer_keys(id) ON DELETE CASCADE,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS sticky_session_unique ON sticky_sessions(consumer_key_id, requested_target_name)`,
      `CREATE INDEX IF NOT EXISTS sticky_session_consumer_idx ON sticky_sessions(consumer_key_id, requested_target_name)`,
      `CREATE INDEX IF NOT EXISTS sticky_session_expires_idx ON sticky_sessions(expires_at)`,
      `CREATE TABLE IF NOT EXISTS circuit_breakers (
         id TEXT PRIMARY KEY,
         upstream_key_id TEXT NOT NULL,
         real_model_name TEXT NOT NULL,
         state TEXT NOT NULL DEFAULT 'closed',
         failure_count INTEGER NOT NULL DEFAULT 0,
         success_count INTEGER NOT NULL DEFAULT 0,
         open_count INTEGER NOT NULL DEFAULT 0,
         opened_at INTEGER,
         cooldown_until INTEGER,
         last_error_code TEXT,
         last_error_message TEXT,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS circuit_breaker_unique ON circuit_breakers(upstream_key_id, real_model_name)`,
      `CREATE INDEX IF NOT EXISTS circuit_breaker_state_idx ON circuit_breakers(state, cooldown_until)`,
      `CREATE INDEX IF NOT EXISTS circuit_breaker_updated_idx ON circuit_breakers(updated_at)`,

      // 可观测性
      `CREATE TABLE IF NOT EXISTS usage_records (
         id TEXT PRIMARY KEY,
         app_id TEXT NOT NULL,
         consumer_key_id TEXT NOT NULL,
         requested_target_name TEXT NOT NULL,
         resolved_target_type TEXT NOT NULL,
         resolved_target_id TEXT NOT NULL,
         upstream_key_id TEXT NOT NULL,
         real_model_name TEXT NOT NULL,
         source_protocol TEXT NOT NULL,
         provider_type TEXT NOT NULL,
         stream INTEGER NOT NULL DEFAULT 0,
         sticky_hit INTEGER NOT NULL DEFAULT 0,
         session_sticky_hit INTEGER NOT NULL DEFAULT 0,
         input_tokens INTEGER,
         output_tokens INTEGER,
         total_tokens INTEGER,
         cache_read_tokens INTEGER,
         cache_write_tokens INTEGER,
         status TEXT NOT NULL,
         error_code TEXT,
         latency_ms INTEGER NOT NULL,
         cost_amount INTEGER,
         cost_currency TEXT,
         created_at INTEGER NOT NULL,
         FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE,
         FOREIGN KEY (consumer_key_id) REFERENCES consumer_keys(id) ON DELETE CASCADE,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE INDEX IF NOT EXISTS usage_records_created_at_idx ON usage_records(created_at)`,
      `CREATE INDEX IF NOT EXISTS usage_records_app_idx ON usage_records(app_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS usage_records_consumer_idx ON usage_records(consumer_key_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS usage_records_upstream_idx ON usage_records(upstream_key_id, created_at)`,
      `CREATE TABLE IF NOT EXISTS request_trace_logs (
         id TEXT PRIMARY KEY,
         request_trace_id TEXT NOT NULL,
         step TEXT NOT NULL,
         step_index INTEGER NOT NULL,
         app_id TEXT,
         consumer_key_id TEXT,
         requested_target_name TEXT,
         upstream_key_id TEXT,
         real_model_name TEXT,
         status TEXT,
         error_code TEXT,
         error_message TEXT,
         details_json TEXT,
         created_at INTEGER NOT NULL
       )`,
      `CREATE INDEX IF NOT EXISTS request_trace_logs_trace_id_idx ON request_trace_logs(request_trace_id)`,
      `CREATE INDEX IF NOT EXISTS request_trace_logs_created_at_idx ON request_trace_logs(created_at)`,
      `CREATE INDEX IF NOT EXISTS request_trace_logs_consumer_idx ON request_trace_logs(consumer_key_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS request_trace_logs_upstream_idx ON request_trace_logs(upstream_key_id, created_at)`,
      `CREATE TABLE IF NOT EXISTS debug_content_logs (
         id TEXT PRIMARY KEY,
         request_trace_id TEXT,
         prompt_json TEXT,
         response_json TEXT,
         input_tokens INTEGER,
         output_tokens INTEGER,
         total_tokens INTEGER,
         created_at INTEGER NOT NULL
       )`,
      `CREATE INDEX IF NOT EXISTS debug_content_logs_trace_id_idx ON debug_content_logs(request_trace_id)`,
      `CREATE INDEX IF NOT EXISTS debug_content_logs_created_at_idx ON debug_content_logs(created_at)`,
      `CREATE TABLE IF NOT EXISTS audit_events (
         id TEXT PRIMARY KEY,
         actor_admin_id TEXT,
         actor_username TEXT,
         action TEXT NOT NULL,
         resource_type TEXT NOT NULL,
         resource_id TEXT,
         details_json TEXT,
         ip TEXT,
         created_at INTEGER NOT NULL
       )`,
      `CREATE INDEX IF NOT EXISTS audit_events_created_at_idx ON audit_events(created_at)`,
      `CREATE INDEX IF NOT EXISTS audit_events_actor_idx ON audit_events(actor_admin_id)`,
      `CREATE INDEX IF NOT EXISTS audit_events_resource_idx ON audit_events(resource_type, resource_id)`,
      `CREATE TABLE IF NOT EXISTS daily_consumption_stats (
         id TEXT PRIMARY KEY,
         upstream_key_id TEXT NOT NULL,
         real_model_name TEXT NOT NULL,
         day_date TEXT NOT NULL,
         request_count INTEGER NOT NULL DEFAULT 0,
         success_count INTEGER NOT NULL DEFAULT 0,
         error_count INTEGER NOT NULL DEFAULT 0,
         input_tokens INTEGER NOT NULL DEFAULT 0,
         output_tokens INTEGER NOT NULL DEFAULT 0,
         total_tokens INTEGER NOT NULL DEFAULT 0,
         cache_read_tokens INTEGER NOT NULL DEFAULT 0,
         cache_write_tokens INTEGER NOT NULL DEFAULT 0,
         avg_latency_ms INTEGER NOT NULL DEFAULT 0,
         total_cost_amount INTEGER NOT NULL DEFAULT 0,
         cost_currency TEXT NOT NULL DEFAULT 'USD',
         updated_at INTEGER NOT NULL
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS daily_consumption_stats_unique ON daily_consumption_stats(upstream_key_id, real_model_name, day_date)`,
      `CREATE INDEX IF NOT EXISTS daily_consumption_stats_day_idx ON daily_consumption_stats(day_date)`,
      `CREATE INDEX IF NOT EXISTS daily_consumption_stats_upstream_idx ON daily_consumption_stats(upstream_key_id, day_date)`,

      // 模型参考
      `CREATE TABLE IF NOT EXISTS model_reference_entries (
         id TEXT PRIMARY KEY,
         region TEXT NOT NULL,
         source TEXT NOT NULL,
         normalized_model_name TEXT NOT NULL,
         source_model_id TEXT NOT NULL,
         display_name TEXT NOT NULL,
         provider TEXT,
         scores_json TEXT NOT NULL DEFAULT '{}',
         price_json TEXT NOT NULL DEFAULT '{}',
         context_window INTEGER,
         latency_ms INTEGER,
         speed_score INTEGER,
         source_url TEXT,
         raw_json TEXT,
         fetched_at INTEGER NOT NULL
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS model_reference_entry_unique ON model_reference_entries(region, source, normalized_model_name)`,
      `CREATE INDEX IF NOT EXISTS model_reference_entry_region_idx ON model_reference_entries(region, source)`,
      `CREATE TABLE IF NOT EXISTS model_reference_sync_status (
         id TEXT PRIMARY KEY,
         region TEXT NOT NULL,
         source TEXT NOT NULL,
         status TEXT NOT NULL DEFAULT 'idle',
         last_refresh_at INTEGER,
         next_refresh_after INTEGER,
         last_error TEXT,
         ttl_ms INTEGER NOT NULL DEFAULT 86400000,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL
       )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS model_reference_sync_unique ON model_reference_sync_status(region, source)`,
      `CREATE INDEX IF NOT EXISTS model_reference_sync_region_idx ON model_reference_sync_status(region)`,

      // 成本账本
      `CREATE TABLE IF NOT EXISTS pricing_entries (
         id TEXT PRIMARY KEY,
         provider_type TEXT NOT NULL,
         upstream_key_id TEXT,
         real_model_name TEXT NOT NULL,
         input_price_per_1k INTEGER NOT NULL,
         output_price_per_1k INTEGER NOT NULL,
         currency TEXT NOT NULL DEFAULT 'USD',
         effective_from INTEGER NOT NULL,
         effective_until INTEGER,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE INDEX IF NOT EXISTS pricing_entries_provider_idx ON pricing_entries(provider_type, real_model_name)`,
      `CREATE INDEX IF NOT EXISTS pricing_entries_upstream_idx ON pricing_entries(upstream_key_id, real_model_name)`,
      `CREATE TABLE IF NOT EXISTS plans (
         id TEXT PRIMARY KEY,
         plan_type TEXT NOT NULL,
         name TEXT NOT NULL,
         provider_type TEXT,
         upstream_key_id TEXT,
         total_amount INTEGER NOT NULL,
         used_amount INTEGER NOT NULL DEFAULT 0,
         remaining_amount INTEGER NOT NULL,
         unit TEXT NOT NULL,
         period TEXT NOT NULL,
         purchased_at INTEGER NOT NULL,
         valid_from INTEGER NOT NULL,
         valid_until INTEGER,
         reminder_days INTEGER NOT NULL DEFAULT 7,
         notes TEXT,
         created_at INTEGER NOT NULL,
         updated_at INTEGER NOT NULL,
         FOREIGN KEY (upstream_key_id) REFERENCES upstream_keys(id) ON DELETE CASCADE
       )`,
      `CREATE INDEX IF NOT EXISTS plans_type_idx ON plans(plan_type)`,
      `CREATE INDEX IF NOT EXISTS plans_upstream_idx ON plans(upstream_key_id)`,
      `CREATE INDEX IF NOT EXISTS plans_valid_until_idx ON plans(valid_until)`,

      // 备份
      `CREATE TABLE IF NOT EXISTS backups (
         id TEXT PRIMARY KEY,
         filename TEXT NOT NULL UNIQUE,
         type TEXT NOT NULL,
         size_bytes INTEGER NOT NULL DEFAULT 0,
         schema_version INTEGER NOT NULL,
         note TEXT,
         created_at INTEGER NOT NULL
       )`,
      `CREATE INDEX IF NOT EXISTS backups_created_at_idx ON backups(created_at)`,
    ],
  },
  {
    version: 2,
    statements: [
      `ALTER TABLE admin_settings ADD COLUMN public_base_url TEXT`,
      `ALTER TABLE admin_settings ADD COLUMN gateway_base_path TEXT DEFAULT '/v1'`,
      `ALTER TABLE admin_settings ADD COLUMN default_request_timeout_ms INTEGER DEFAULT 30000`,
      `ALTER TABLE admin_settings ADD COLUMN default_retries INTEGER DEFAULT 0`,
      `ALTER TABLE admin_settings ADD COLUMN enable_sticky_session INTEGER DEFAULT 1`,
      `ALTER TABLE admin_settings ADD COLUMN enable_circuit_breaker INTEGER DEFAULT 1`,
    ],
  },
  {
    version: 3,
    statements: [
      `ALTER TABLE usage_records ADD COLUMN request_trace_id TEXT`,
      `CREATE INDEX IF NOT EXISTS usage_records_trace_idx ON usage_records(request_trace_id)`,
    ],
  },
  {
    version: 4,
    statements: [
      `ALTER TABLE admin_settings ADD COLUMN content_log_expires_at INTEGER`,
      `ALTER TABLE admin_settings ADD COLUMN content_log_max_rows INTEGER NOT NULL DEFAULT 1000`,
    ],
  },
  {
    version: 5,
    statements: [
      `ALTER TABLE model_reference_entries ADD COLUMN created_at INTEGER NOT NULL DEFAULT 0`,
      `ALTER TABLE model_reference_entries ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0`,
    ],
  },
];
